### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by pgcudahy** [jodyphelan/NTM-Profiler#19]
Hey Jody, thanks for your help and the great tool. I'm writing up some results for publication and wanted to know how'd you'd want ntm-profiler cited. Maybe get a [zenodo](https://zenodo.org/) DOI?

**Comment by jodyphelan** [comment]
Hi @pgcudahy,

Thanks for using the tool, glad it was useful. I've created a zendodo DOI for the latest release (v0.2.1). 

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7078796.svg)](https://doi.org/10.5281/zenodo.7078796)
