### ISSUE TITLE
NTM resistance mutation database and drug resistance prediction. 

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/NTM-Profiler#2]
It would be great to add resistance prediction capabilities similar to what is available for TB Profiler.   Is there a known database of resistance mutations for NTM?

**Comment by jodyphelan** [comment]
From what I have seen it is mostly scattered in the literature (e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3028756/). I haven't come across a central database, though I could have missed it. I'm happy to make a start for some of the most clinically relevant NTMs.

**Comment by harrismia** [comment]
That would be great! It might be good to have a similar separate database (similar to tbdb for TB Profiler) that can be updated as new variants are reported in the literature.     ntmdb ?     I guess this would also need to include the name of the NTM ?

**Comment by harrismia** [comment]
One more publication:  [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6325232/](url)
